GET http://localhost:8080/users/6108ac8d0a048214c901ed1c/posts

# POST http://localhost:8080/users/
# content-type: application/json

# {
#     "name": "Jose",
#     "email": "jose@gmail.com"
# }


# PUT http://localhost:8080/users/6108a4400a04820ae4381ff4
# content-type: application/json

# {
#     "name": "João Marcus",
#     "email": "joao@gmail.com"
# }
